import type { ProviderCapabilities } from "./types.ts";

/**
 * Providers NYX does not call.
 * Each one was checked against its current developer terms. None of these expose a
 * raw full-track file this app is allowed to stream or download.
 */
export const DISABLED_PROVIDER_CAPABILITIES: ProviderCapabilities[] = [
  {
    provider: "spotify",
    enabled: false,
    disabledReason:
      "The Spotify Web API returns catalog metadata only. Playback stays inside the Spotify client for an authorized Premium listener. It does not give third-party apps a full-track audio URL, and preview URLs are not a full song.",
    searchSupported: false,
    metadataSupported: false,
    fullTrackPlaybackSupported: false,
    previewSupported: false,
    officialPlayerSupported: false,
    downloadSupported: false,
    commercialUseAllowed: false,
    streamingRestrictions: "Playback requires the Spotify client and the listener's own account. NYX does not receive the audio.",
    downloadRestrictions: "Downloading Spotify audio is not permitted.",
    attributionRequired: true,
    authenticationRequired: true,
    apiRateLimit: "Development mode is quota-limited and is not a playback license.",
    territoryRestrictions: "Spotify catalog rights vary by country.",
    licenseInformation: "Spotify controls the sound recordings. API access is not a sync or download license.",
    officialDocumentationUrl: "https://developer.spotify.com/documentation/web-api",
    credentials: ["SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"],
  },
  {
    provider: "soundcloud",
    enabled: false,
    disabledReason:
      "SoundCloud's public API terms forbid downloading or storing their content and forbid mixing it with other content such as a social video. Commercial use of the public API is not allowed. NYX will not stream or download SoundCloud audio.",
    searchSupported: false,
    metadataSupported: false,
    fullTrackPlaybackSupported: false,
    previewSupported: false,
    officialPlayerSupported: false,
    downloadSupported: false,
    commercialUseAllowed: false,
    streamingRestrictions: "Public API playback is partner-scoped. Progressive MP3 download URLs were removed from the streams endpoint.",
    downloadRestrictions: "Downloading SoundCloud content is prohibited.",
    attributionRequired: true,
    authenticationRequired: true,
    apiRateLimit: "About 15,000 play-stream requests per day per client, and that quota is not a license to rehost audio.",
    territoryRestrictions: "Track access can be playable, preview, or blocked.",
    licenseInformation: "Sound recordings belong to the rightsholders. The public API is not a catalog license for NYX.",
    officialDocumentationUrl: "https://developers.soundcloud.com/docs/api/terms-of-use",
    credentials: ["SOUNDCLOUD_CLIENT_ID"],
  },
  {
    provider: "youtube",
    enabled: false,
    disabledReason:
      "YouTube's developer policies prohibit downloading videos, separating the audio, and background playback of embedded videos. NYX will not turn YouTube into an audio catalog.",
    searchSupported: false,
    metadataSupported: false,
    fullTrackPlaybackSupported: false,
    previewSupported: false,
    officialPlayerSupported: false,
    downloadSupported: false,
    commercialUseAllowed: false,
    streamingRestrictions: "Embedded playback must stay inside YouTube's player, with ads and context intact, and must not play in the background.",
    downloadRestrictions: "Saving YouTube audiovisual content or isolating its audio is prohibited.",
    attributionRequired: true,
    authenticationRequired: true,
    apiRateLimit: "YouTube Data API quota is separate from a content license.",
    territoryRestrictions: "Rights owners can block embedding and territories.",
    licenseInformation: "A Data API search result is not permission to play the sound recording inside NYX.",
    officialDocumentationUrl: "https://developers.google.com/youtube/terms/developer-policies",
    credentials: ["YOUTUBE_API_KEY"],
  },
  {
    provider: "freemusicarchive",
    enabled: false,
    disabledReason:
      "Free Music Archive shut down its developer API and forbids hotlinking files on its servers and forwarding user searches into its site. NYX does not scrape FMA.",
    searchSupported: false,
    metadataSupported: false,
    fullTrackPlaybackSupported: false,
    previewSupported: false,
    officialPlayerSupported: false,
    downloadSupported: false,
    commercialUseAllowed: false,
    streamingRestrictions: "FMA does not allow apps to play files hosted on freemusicarchive.org.",
    downloadRestrictions: "Bulk or automated downloading is not offered through an API.",
    attributionRequired: true,
    authenticationRequired: false,
    apiRateLimit: "No public API.",
    territoryRestrictions: "None published for an API that is closed.",
    licenseInformation: "Artist Creative Commons licenses still apply to files a person downloads themselves. That is not an app streaming grant.",
    officialDocumentationUrl: "https://freemusicarchive.org/app-developers",
    credentials: [],
  },
  {
    provider: "apple-musickit",
    enabled: false,
    disabledReason:
      "Apple MusicKit can play full songs only inside Apple's player for a listener who has Apple Music. It does not give NYX the song file. NYX uses the public iTunes Search API for metadata and Apple's official embed, and does not ship a MusicKit private key.",
    searchSupported: false,
    metadataSupported: false,
    fullTrackPlaybackSupported: false,
    previewSupported: false,
    officialPlayerSupported: false,
    downloadSupported: false,
    commercialUseAllowed: false,
    streamingRestrictions: "Full playback requires MusicKit, a developer token, and the listener's Apple Music subscription.",
    downloadRestrictions: "Apple Music downloads stay inside Apple's apps.",
    attributionRequired: true,
    authenticationRequired: true,
    apiRateLimit: "MusicKit tokens are short-lived and app-specific.",
    territoryRestrictions: "Apple Music rights are storefront-specific.",
    licenseInformation: "The iTunes Search API preview and the Apple Music embed are the only Apple playback paths NYX enables.",
    officialDocumentationUrl: "https://developer.apple.com/documentation/musickit",
    credentials: ["APPLE_MUSIC_TEAM_ID", "APPLE_MUSIC_KEY_ID", "APPLE_MUSIC_PRIVATE_KEY"],
  },
];
