/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppCaptureRouteImport } from './routes/_app/capture'
import { Route as AppCardRouteImport } from './routes/_app/card'
import { Route as AppChallengesRouteImport } from './routes/_app/challenges'
import { Route as AppCoinsRouteImport } from './routes/_app/coins'
import { Route as AppCommunitiesRouteImport } from './routes/_app/communities'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppKaiRouteImport } from './routes/_app/kai'
import { Route as AppListsRouteImport } from './routes/_app/lists'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppMemoriesRouteImport } from './routes/_app/memories'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppPlusRouteImport } from './routes/_app/plus'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStickersRouteImport } from './routes/_app/stickers'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as AppSuperomniRouteImport } from './routes/_app/superomni'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppVerify2faRouteImport } from './routes/_app/verify-2fa'
import { Route as AppWatchRouteImport } from './routes/_app/watch'
import { Route as ApiMusicDownloadRouteImport } from './routes/api/music-download'
import { Route as ApiMusicStreamRouteImport } from './routes/api/music-stream'
import { Route as ApiNyxReplyRouteImport } from './routes/api/nyx-reply'
import { Route as ApiNyxStreamRouteImport } from './routes/api/nyx-stream'
import { Route as ApiOmniStreamRouteImport } from './routes/api/omni-stream'
import { Route as ApiOmniTtsRouteImport } from './routes/api/omni-tts'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as AppCUsernameRouteImport } from './routes/_app/c.$username'
import { Route as AppCallIdRouteImport } from './routes/_app/call.$id'
import { Route as AppCommunitiesIdRouteImport } from './routes/_app/communities.$id'
import { Route as AppFlashIdRouteImport } from './routes/_app/flash.$id'
import { Route as AppHlIdRouteImport } from './routes/_app/hl.$id'
import { Route as AppInboxIdRouteImport } from './routes/_app/inbox.$id'
import { Route as AppJoinTokenRouteImport } from './routes/_app/join.$token'
import { Route as AppListsIdRouteImport } from './routes/_app/lists.$id'
import { Route as AppLiveIdRouteImport } from './routes/_app/live.$id'
import { Route as AppPIdRouteImport } from './routes/_app/p.$id'
import { Route as AppPlusIndexRouteImport } from './routes/_app/plus.index'
import { Route as AppPlusAiRouteImport } from './routes/_app/plus.ai'
import { Route as AppStatusIdRouteImport } from './routes/_app/status.$id'
import { Route as AppStickersIndexRouteImport } from './routes/_app/stickers.index'
import { Route as AppStickersCreateRouteImport } from './routes/_app/stickers.create'
import { Route as AppStoryIdRouteImport } from './routes/_app/story.$id'
import { Route as AppSupportIdRouteImport } from './routes/_app/support.$id'
import { Route as AppTagTagRouteImport } from './routes/_app/tag.$tag'
import { Route as AppUUsernameRouteImport } from './routes/_app/u.$username'
import { Route as ApiAiStatusRouteImport } from './routes/api/ai/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingAppleRouteImport } from './routes/api/billing/apple'
import { Route as ApiBillingGoogleRouteImport } from './routes/api/billing/google'
import { Route as ApiBillingWebRouteImport } from './routes/api/billing/web'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiMediaCompleteRouteImport } from './routes/api/media/complete'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiVideoTaskIdRouteImport } from './routes/api/video/$taskId'
import { Route as ApiVideoGenerateRouteImport } from './routes/api/video/generate'
import { Route as ApiMusicTrackIdDownloadRouteImport } from './routes/api/music/$trackId/download'
import { Route as ApiVideoStatusTaskIdRouteImport } from './routes/api/video/status/$taskId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCardRoute = AppCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoinsRoute = AppCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunitiesRoute = AppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKaiRoute = AppKaiRouteImport.update({
  id: '/kai',
  path: '/kai',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListsRoute = AppListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlusRoute = AppPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStickersRoute = AppStickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuperomniRoute = AppSuperomniRouteImport.update({
  id: '/superomni',
  path: '/superomni',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVerify2faRoute = AppVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiMusicDownloadRoute = ApiMusicDownloadRouteImport.update({
  id: '/api/music-download',
  path: '/api/music-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicStreamRoute = ApiMusicStreamRouteImport.update({
  id: '/api/music-stream',
  path: '/api/music-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNyxReplyRoute = ApiNyxReplyRouteImport.update({
  id: '/api/nyx-reply',
  path: '/api/nyx-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNyxStreamRoute = ApiNyxStreamRouteImport.update({
  id: '/api/nyx-stream',
  path: '/api/nyx-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOmniStreamRoute = ApiOmniStreamRouteImport.update({
  id: '/api/omni-stream',
  path: '/api/omni-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOmniTtsRoute = ApiOmniTtsRouteImport.update({
  id: '/api/omni-tts',
  path: '/api/omni-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCUsernameRoute = AppCUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCallIdRoute = AppCallIdRouteImport.update({
  id: '/call/$id',
  path: '/call/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunitiesIdRoute = AppCommunitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCommunitiesRoute,
} as any)
const AppFlashIdRoute = AppFlashIdRouteImport.update({
  id: '/flash/$id',
  path: '/flash/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHlIdRoute = AppHlIdRouteImport.update({
  id: '/hl/$id',
  path: '/hl/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppJoinTokenRoute = AppJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListsIdRoute = AppListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppListsRoute,
} as any)
const AppLiveIdRoute = AppLiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLiveRoute,
} as any)
const AppPIdRoute = AppPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlusIndexRoute = AppPlusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlusRoute,
} as any)
const AppPlusAiRoute = AppPlusAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppPlusRoute,
} as any)
const AppStatusIdRoute = AppStatusIdRouteImport.update({
  id: '/status/$id',
  path: '/status/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStickersIndexRoute = AppStickersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStickersRoute,
} as any)
const AppStickersCreateRoute = AppStickersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppStickersRoute,
} as any)
const AppStoryIdRoute = AppStoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSupportIdRoute = AppSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSupportRoute,
} as any)
const AppTagTagRoute = AppTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUUsernameRoute = AppUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAiStatusRoute = ApiAiStatusRouteImport.update({
  id: '/api/ai/status',
  path: '/api/ai/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingAppleRoute = ApiBillingAppleRouteImport.update({
  id: '/api/billing/apple',
  path: '/api/billing/apple',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingGoogleRoute = ApiBillingGoogleRouteImport.update({
  id: '/api/billing/google',
  path: '/api/billing/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebRoute = ApiBillingWebRouteImport.update({
  id: '/api/billing/web',
  path: '/api/billing/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaCompleteRoute = ApiMediaCompleteRouteImport.update({
  id: '/api/media/complete',
  path: '/api/media/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoTaskIdRoute = ApiVideoTaskIdRouteImport.update({
  id: '/api/video/$taskId',
  path: '/api/video/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenerateRoute = ApiVideoGenerateRouteImport.update({
  id: '/api/video/generate',
  path: '/api/video/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicTrackIdDownloadRoute = ApiMusicTrackIdDownloadRouteImport.update({
  id: '/api/music/$trackId/download',
  path: '/api/music/$trackId/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStatusTaskIdRoute = ApiVideoStatusTaskIdRouteImport.update({
  id: '/api/video/status/$taskId',
  path: '/api/video/status/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/capture': typeof AppCaptureRoute
  '/card': typeof AppCardRoute
  '/challenges': typeof AppChallengesRoute
  '/coins': typeof AppCoinsRoute
  '/communities': typeof AppCommunitiesRouteWithChildren
  '/create': typeof AppCreateRoute
  '/discover': typeof AppDiscoverRoute
  '/events': typeof AppEventsRoute
  '/friends': typeof AppFriendsRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/kai': typeof AppKaiRoute
  '/lists': typeof AppListsRouteWithChildren
  '/live': typeof AppLiveRouteWithChildren
  '/map': typeof AppMapRoute
  '/me': typeof AppMeRoute
  '/memories': typeof AppMemoriesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/plus': typeof AppPlusRouteWithChildren
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/stickers': typeof AppStickersRouteWithChildren
  '/studio': typeof AppStudioRoute
  '/superomni': typeof AppSuperomniRoute
  '/support': typeof AppSupportRouteWithChildren
  '/verify-2fa': typeof AppVerify2faRoute
  '/watch': typeof AppWatchRoute
  '/api/music-download': typeof ApiMusicDownloadRoute
  '/api/music-stream': typeof ApiMusicStreamRoute
  '/api/nyx-reply': typeof ApiNyxReplyRoute
  '/api/nyx-stream': typeof ApiNyxStreamRoute
  '/api/omni-stream': typeof ApiOmniStreamRoute
  '/api/omni-tts': typeof ApiOmniTtsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/s/$id': typeof SIdRoute
  '/c/$username': typeof AppCUsernameRoute
  '/call/$id': typeof AppCallIdRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/flash/$id': typeof AppFlashIdRoute
  '/hl/$id': typeof AppHlIdRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/lists/$id': typeof AppListsIdRoute
  '/live/$id': typeof AppLiveIdRoute
  '/p/$id': typeof AppPIdRoute
  '/plus/ai': typeof AppPlusAiRoute
  '/status/$id': typeof AppStatusIdRoute
  '/stickers/create': typeof AppStickersCreateRoute
  '/story/$id': typeof AppStoryIdRoute
  '/support/$id': typeof AppSupportIdRoute
  '/tag/$tag': typeof AppTagTagRoute
  '/u/$username': typeof AppUUsernameRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/apple': typeof ApiBillingAppleRoute
  '/api/billing/google': typeof ApiBillingGoogleRoute
  '/api/billing/web': typeof ApiBillingWebRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/complete': typeof ApiMediaCompleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/video/$taskId': typeof ApiVideoTaskIdRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/plus/': typeof AppPlusIndexRoute
  '/stickers/': typeof AppStickersIndexRoute
  '/api/music/$trackId/download': typeof ApiMusicTrackIdDownloadRoute
  '/api/video/status/$taskId': typeof ApiVideoStatusTaskIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/alerts': typeof AppAlertsRoute
  '/capture': typeof AppCaptureRoute
  '/card': typeof AppCardRoute
  '/challenges': typeof AppChallengesRoute
  '/coins': typeof AppCoinsRoute
  '/communities': typeof AppCommunitiesRouteWithChildren
  '/create': typeof AppCreateRoute
  '/discover': typeof AppDiscoverRoute
  '/events': typeof AppEventsRoute
  '/friends': typeof AppFriendsRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/kai': typeof AppKaiRoute
  '/lists': typeof AppListsRouteWithChildren
  '/live': typeof AppLiveRouteWithChildren
  '/map': typeof AppMapRoute
  '/me': typeof AppMeRoute
  '/memories': typeof AppMemoriesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRoute
  '/superomni': typeof AppSuperomniRoute
  '/support': typeof AppSupportRouteWithChildren
  '/verify-2fa': typeof AppVerify2faRoute
  '/watch': typeof AppWatchRoute
  '/api/music-download': typeof ApiMusicDownloadRoute
  '/api/music-stream': typeof ApiMusicStreamRoute
  '/api/nyx-reply': typeof ApiNyxReplyRoute
  '/api/nyx-stream': typeof ApiNyxStreamRoute
  '/api/omni-stream': typeof ApiOmniStreamRoute
  '/api/omni-tts': typeof ApiOmniTtsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/s/$id': typeof SIdRoute
  '/': typeof AppIndexRoute
  '/c/$username': typeof AppCUsernameRoute
  '/call/$id': typeof AppCallIdRoute
  '/communities/$id': typeof AppCommunitiesIdRoute
  '/flash/$id': typeof AppFlashIdRoute
  '/hl/$id': typeof AppHlIdRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/join/$token': typeof AppJoinTokenRoute
  '/lists/$id': typeof AppListsIdRoute
  '/live/$id': typeof AppLiveIdRoute
  '/p/$id': typeof AppPIdRoute
  '/plus/ai': typeof AppPlusAiRoute
  '/status/$id': typeof AppStatusIdRoute
  '/stickers/create': typeof AppStickersCreateRoute
  '/story/$id': typeof AppStoryIdRoute
  '/support/$id': typeof AppSupportIdRoute
  '/tag/$tag': typeof AppTagTagRoute
  '/u/$username': typeof AppUUsernameRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/apple': typeof ApiBillingAppleRoute
  '/api/billing/google': typeof ApiBillingGoogleRoute
  '/api/billing/web': typeof ApiBillingWebRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/complete': typeof ApiMediaCompleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/video/$taskId': typeof ApiVideoTaskIdRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/plus': typeof AppPlusIndexRoute
  '/stickers': typeof AppStickersIndexRoute
  '/api/music/$trackId/download': typeof ApiMusicTrackIdDownloadRoute
  '/api/video/status/$taskId': typeof ApiVideoStatusTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/capture': typeof AppCaptureRoute
  '/_app/card': typeof AppCardRoute
  '/_app/challenges': typeof AppChallengesRoute
  '/_app/coins': typeof AppCoinsRoute
  '/_app/communities': typeof AppCommunitiesRouteWithChildren
  '/_app/create': typeof AppCreateRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/kai': typeof AppKaiRoute
  '/_app/lists': typeof AppListsRouteWithChildren
  '/_app/live': typeof AppLiveRouteWithChildren
  '/_app/map': typeof AppMapRoute
  '/_app/me': typeof AppMeRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/plus': typeof AppPlusRouteWithChildren
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stickers': typeof AppStickersRouteWithChildren
  '/_app/studio': typeof AppStudioRoute
  '/_app/superomni': typeof AppSuperomniRoute
  '/_app/support': typeof AppSupportRouteWithChildren
  '/_app/verify-2fa': typeof AppVerify2faRoute
  '/_app/watch': typeof AppWatchRoute
  '/api/music-download': typeof ApiMusicDownloadRoute
  '/api/music-stream': typeof ApiMusicStreamRoute
  '/api/nyx-reply': typeof ApiNyxReplyRoute
  '/api/nyx-stream': typeof ApiNyxStreamRoute
  '/api/omni-stream': typeof ApiOmniStreamRoute
  '/api/omni-tts': typeof ApiOmniTtsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/s/$id': typeof SIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$username': typeof AppCUsernameRoute
  '/_app/call/$id': typeof AppCallIdRoute
  '/_app/communities/$id': typeof AppCommunitiesIdRoute
  '/_app/flash/$id': typeof AppFlashIdRoute
  '/_app/hl/$id': typeof AppHlIdRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/join/$token': typeof AppJoinTokenRoute
  '/_app/lists/$id': typeof AppListsIdRoute
  '/_app/live/$id': typeof AppLiveIdRoute
  '/_app/p/$id': typeof AppPIdRoute
  '/_app/plus/ai': typeof AppPlusAiRoute
  '/_app/status/$id': typeof AppStatusIdRoute
  '/_app/stickers/create': typeof AppStickersCreateRoute
  '/_app/story/$id': typeof AppStoryIdRoute
  '/_app/support/$id': typeof AppSupportIdRoute
  '/_app/tag/$tag': typeof AppTagTagRoute
  '/_app/u/$username': typeof AppUUsernameRoute
  '/api/ai/status': typeof ApiAiStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/apple': typeof ApiBillingAppleRoute
  '/api/billing/google': typeof ApiBillingGoogleRoute
  '/api/billing/web': typeof ApiBillingWebRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/media/complete': typeof ApiMediaCompleteRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/video/$taskId': typeof ApiVideoTaskIdRoute
  '/api/video/generate': typeof ApiVideoGenerateRoute
  '/_app/plus/': typeof AppPlusIndexRoute
  '/_app/stickers/': typeof AppStickersIndexRoute
  '/api/music/$trackId/download': typeof ApiMusicTrackIdDownloadRoute
  '/api/video/status/$taskId': typeof ApiVideoStatusTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin'
    | '/alerts'
    | '/capture'
    | '/card'
    | '/challenges'
    | '/coins'
    | '/communities'
    | '/create'
    | '/discover'
    | '/events'
    | '/friends'
    | '/inbox'
    | '/kai'
    | '/lists'
    | '/live'
    | '/map'
    | '/me'
    | '/memories'
    | '/onboarding'
    | '/plus'
    | '/saved'
    | '/settings'
    | '/stickers'
    | '/studio'
    | '/superomni'
    | '/support'
    | '/verify-2fa'
    | '/watch'
    | '/api/music-download'
    | '/api/music-stream'
    | '/api/nyx-reply'
    | '/api/nyx-stream'
    | '/api/omni-stream'
    | '/api/omni-tts'
    | '/api/rtc'
    | '/s/$id'
    | '/c/$username'
    | '/call/$id'
    | '/communities/$id'
    | '/flash/$id'
    | '/hl/$id'
    | '/inbox/$id'
    | '/join/$token'
    | '/lists/$id'
    | '/live/$id'
    | '/p/$id'
    | '/plus/ai'
    | '/status/$id'
    | '/stickers/create'
    | '/story/$id'
    | '/support/$id'
    | '/tag/$tag'
    | '/u/$username'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/billing/apple'
    | '/api/billing/google'
    | '/api/billing/web'
    | '/api/media/$id'
    | '/api/media/complete'
    | '/api/media/upload'
    | '/api/video/$taskId'
    | '/api/video/generate'
    | '/plus/'
    | '/stickers/'
    | '/api/music/$trackId/download'
    | '/api/video/status/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin'
    | '/alerts'
    | '/capture'
    | '/card'
    | '/challenges'
    | '/coins'
    | '/communities'
    | '/create'
    | '/discover'
    | '/events'
    | '/friends'
    | '/inbox'
    | '/kai'
    | '/lists'
    | '/live'
    | '/map'
    | '/me'
    | '/memories'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/studio'
    | '/superomni'
    | '/support'
    | '/verify-2fa'
    | '/watch'
    | '/api/music-download'
    | '/api/music-stream'
    | '/api/nyx-reply'
    | '/api/nyx-stream'
    | '/api/omni-stream'
    | '/api/omni-tts'
    | '/api/rtc'
    | '/s/$id'
    | '/'
    | '/c/$username'
    | '/call/$id'
    | '/communities/$id'
    | '/flash/$id'
    | '/hl/$id'
    | '/inbox/$id'
    | '/join/$token'
    | '/lists/$id'
    | '/live/$id'
    | '/p/$id'
    | '/plus/ai'
    | '/status/$id'
    | '/stickers/create'
    | '/story/$id'
    | '/support/$id'
    | '/tag/$tag'
    | '/u/$username'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/billing/apple'
    | '/api/billing/google'
    | '/api/billing/web'
    | '/api/media/$id'
    | '/api/media/complete'
    | '/api/media/upload'
    | '/api/video/$taskId'
    | '/api/video/generate'
    | '/plus'
    | '/stickers'
    | '/api/music/$trackId/download'
    | '/api/video/status/$taskId'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/admin'
    | '/_app/alerts'
    | '/_app/capture'
    | '/_app/card'
    | '/_app/challenges'
    | '/_app/coins'
    | '/_app/communities'
    | '/_app/create'
    | '/_app/discover'
    | '/_app/events'
    | '/_app/friends'
    | '/_app/inbox'
    | '/_app/kai'
    | '/_app/lists'
    | '/_app/live'
    | '/_app/map'
    | '/_app/me'
    | '/_app/memories'
    | '/_app/onboarding'
    | '/_app/plus'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/stickers'
    | '/_app/studio'
    | '/_app/superomni'
    | '/_app/support'
    | '/_app/verify-2fa'
    | '/_app/watch'
    | '/api/music-download'
    | '/api/music-stream'
    | '/api/nyx-reply'
    | '/api/nyx-stream'
    | '/api/omni-stream'
    | '/api/omni-tts'
    | '/api/rtc'
    | '/s/$id'
    | '/_app/'
    | '/_app/c/$username'
    | '/_app/call/$id'
    | '/_app/communities/$id'
    | '/_app/flash/$id'
    | '/_app/hl/$id'
    | '/_app/inbox/$id'
    | '/_app/join/$token'
    | '/_app/lists/$id'
    | '/_app/live/$id'
    | '/_app/p/$id'
    | '/_app/plus/ai'
    | '/_app/status/$id'
    | '/_app/stickers/create'
    | '/_app/story/$id'
    | '/_app/support/$id'
    | '/_app/tag/$tag'
    | '/_app/u/$username'
    | '/api/ai/status'
    | '/api/auth/$'
    | '/api/billing/apple'
    | '/api/billing/google'
    | '/api/billing/web'
    | '/api/media/$id'
    | '/api/media/complete'
    | '/api/media/upload'
    | '/api/video/$taskId'
    | '/api/video/generate'
    | '/_app/plus/'
    | '/_app/stickers/'
    | '/api/music/$trackId/download'
    | '/api/video/status/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiMusicDownloadRoute: typeof ApiMusicDownloadRoute
  ApiMusicStreamRoute: typeof ApiMusicStreamRoute
  ApiNyxReplyRoute: typeof ApiNyxReplyRoute
  ApiNyxStreamRoute: typeof ApiNyxStreamRoute
  ApiOmniStreamRoute: typeof ApiOmniStreamRoute
  ApiOmniTtsRoute: typeof ApiOmniTtsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  SIdRoute: typeof SIdRoute
  ApiAiStatusRoute: typeof ApiAiStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingAppleRoute: typeof ApiBillingAppleRoute
  ApiBillingGoogleRoute: typeof ApiBillingGoogleRoute
  ApiBillingWebRoute: typeof ApiBillingWebRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiMediaCompleteRoute: typeof ApiMediaCompleteRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiVideoTaskIdRoute: typeof ApiVideoTaskIdRoute
  ApiVideoGenerateRoute: typeof ApiVideoGenerateRoute
  ApiMusicTrackIdDownloadRoute: typeof ApiMusicTrackIdDownloadRoute
  ApiVideoStatusTaskIdRoute: typeof ApiVideoStatusTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/capture': {
      id: '/_app/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/card': {
      id: '/_app/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof AppCardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/challenges': {
      id: '/_app/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/coins': {
      id: '/_app/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof AppCoinsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities': {
      id: '/_app/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AppCommunitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kai': {
      id: '/_app/kai'
      path: '/kai'
      fullPath: '/kai'
      preLoaderRoute: typeof AppKaiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lists': {
      id: '/_app/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AppListsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plus': {
      id: '/_app/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AppPlusRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stickers': {
      id: '/_app/stickers'
      path: '/stickers'
      fullPath: '/stickers'
      preLoaderRoute: typeof AppStickersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/superomni': {
      id: '/_app/superomni'
      path: '/superomni'
      fullPath: '/superomni'
      preLoaderRoute: typeof AppSuperomniRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/verify-2fa': {
      id: '/_app/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof AppVerify2faRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/music-download': {
      id: '/api/music-download'
      path: '/api/music-download'
      fullPath: '/api/music-download'
      preLoaderRoute: typeof ApiMusicDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music-stream': {
      id: '/api/music-stream'
      path: '/api/music-stream'
      fullPath: '/api/music-stream'
      preLoaderRoute: typeof ApiMusicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nyx-reply': {
      id: '/api/nyx-reply'
      path: '/api/nyx-reply'
      fullPath: '/api/nyx-reply'
      preLoaderRoute: typeof ApiNyxReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nyx-stream': {
      id: '/api/nyx-stream'
      path: '/api/nyx-stream'
      fullPath: '/api/nyx-stream'
      preLoaderRoute: typeof ApiNyxStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/omni-stream': {
      id: '/api/omni-stream'
      path: '/api/omni-stream'
      fullPath: '/api/omni-stream'
      preLoaderRoute: typeof ApiOmniStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/omni-tts': {
      id: '/api/omni-tts'
      path: '/api/omni-tts'
      fullPath: '/api/omni-tts'
      preLoaderRoute: typeof ApiOmniTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/c/$username': {
      id: '/_app/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof AppCUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/call/$id': {
      id: '/_app/call/$id'
      path: '/call/$id'
      fullPath: '/call/$id'
      preLoaderRoute: typeof AppCallIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communities/$id': {
      id: '/_app/communities/$id'
      path: '/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof AppCommunitiesIdRouteImport
      parentRoute: typeof AppCommunitiesRoute
    }
    '/_app/flash/$id': {
      id: '/_app/flash/$id'
      path: '/flash/$id'
      fullPath: '/flash/$id'
      preLoaderRoute: typeof AppFlashIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hl/$id': {
      id: '/_app/hl/$id'
      path: '/hl/$id'
      fullPath: '/hl/$id'
      preLoaderRoute: typeof AppHlIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/join/$token': {
      id: '/_app/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof AppJoinTokenRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lists/$id': {
      id: '/_app/lists/$id'
      path: '/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof AppListsIdRouteImport
      parentRoute: typeof AppListsRoute
    }
    '/_app/live/$id': {
      id: '/_app/live/$id'
      path: '/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof AppLiveIdRouteImport
      parentRoute: typeof AppLiveRoute
    }
    '/_app/p/$id': {
      id: '/_app/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof AppPIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/plus/': {
      id: '/_app/plus/'
      path: '/'
      fullPath: '/plus/'
      preLoaderRoute: typeof AppPlusIndexRouteImport
      parentRoute: typeof AppPlusRoute
    }
    '/_app/plus/ai': {
      id: '/_app/plus/ai'
      path: '/ai'
      fullPath: '/plus/ai'
      preLoaderRoute: typeof AppPlusAiRouteImport
      parentRoute: typeof AppPlusRoute
    }
    '/_app/status/$id': {
      id: '/_app/status/$id'
      path: '/status/$id'
      fullPath: '/status/$id'
      preLoaderRoute: typeof AppStatusIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/stickers/': {
      id: '/_app/stickers/'
      path: '/'
      fullPath: '/stickers/'
      preLoaderRoute: typeof AppStickersIndexRouteImport
      parentRoute: typeof AppStickersRoute
    }
    '/_app/stickers/create': {
      id: '/_app/stickers/create'
      path: '/create'
      fullPath: '/stickers/create'
      preLoaderRoute: typeof AppStickersCreateRouteImport
      parentRoute: typeof AppStickersRoute
    }
    '/_app/story/$id': {
      id: '/_app/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof AppStoryIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/support/$id': {
      id: '/_app/support/$id'
      path: '/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof AppSupportIdRouteImport
      parentRoute: typeof AppSupportRoute
    }
    '/_app/tag/$tag': {
      id: '/_app/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof AppTagTagRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/u/$username': {
      id: '/_app/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AppUUsernameRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/ai/status': {
      id: '/api/ai/status'
      path: '/api/ai/status'
      fullPath: '/api/ai/status'
      preLoaderRoute: typeof ApiAiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/apple': {
      id: '/api/billing/apple'
      path: '/api/billing/apple'
      fullPath: '/api/billing/apple'
      preLoaderRoute: typeof ApiBillingAppleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/google': {
      id: '/api/billing/google'
      path: '/api/billing/google'
      fullPath: '/api/billing/google'
      preLoaderRoute: typeof ApiBillingGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/web': {
      id: '/api/billing/web'
      path: '/api/billing/web'
      fullPath: '/api/billing/web'
      preLoaderRoute: typeof ApiBillingWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/complete': {
      id: '/api/media/complete'
      path: '/api/media/complete'
      fullPath: '/api/media/complete'
      preLoaderRoute: typeof ApiMediaCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/$taskId': {
      id: '/api/video/$taskId'
      path: '/api/video/$taskId'
      fullPath: '/api/video/$taskId'
      preLoaderRoute: typeof ApiVideoTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/generate': {
      id: '/api/video/generate'
      path: '/api/video/generate'
      fullPath: '/api/video/generate'
      preLoaderRoute: typeof ApiVideoGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music/$trackId/download': {
      id: '/api/music/$trackId/download'
      path: '/api/music/$trackId/download'
      fullPath: '/api/music/$trackId/download'
      preLoaderRoute: typeof ApiMusicTrackIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/status/$taskId': {
      id: '/api/video/status/$taskId'
      path: '/api/video/status/$taskId'
      fullPath: '/api/video/status/$taskId'
      preLoaderRoute: typeof ApiVideoStatusTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCommunitiesRouteChildren {
  AppCommunitiesIdRoute: typeof AppCommunitiesIdRoute
}

const AppCommunitiesRouteChildren: AppCommunitiesRouteChildren = {
  AppCommunitiesIdRoute: AppCommunitiesIdRoute,
}

const AppCommunitiesRouteWithChildren = AppCommunitiesRoute._addFileChildren(
  AppCommunitiesRouteChildren,
)

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppListsRouteChildren {
  AppListsIdRoute: typeof AppListsIdRoute
}

const AppListsRouteChildren: AppListsRouteChildren = {
  AppListsIdRoute: AppListsIdRoute,
}

const AppListsRouteWithChildren = AppListsRoute._addFileChildren(
  AppListsRouteChildren,
)

interface AppLiveRouteChildren {
  AppLiveIdRoute: typeof AppLiveIdRoute
}

const AppLiveRouteChildren: AppLiveRouteChildren = {
  AppLiveIdRoute: AppLiveIdRoute,
}

const AppLiveRouteWithChildren =
  AppLiveRoute._addFileChildren(AppLiveRouteChildren)

interface AppPlusRouteChildren {
  AppPlusAiRoute: typeof AppPlusAiRoute
  AppPlusIndexRoute: typeof AppPlusIndexRoute
}

const AppPlusRouteChildren: AppPlusRouteChildren = {
  AppPlusAiRoute: AppPlusAiRoute,
  AppPlusIndexRoute: AppPlusIndexRoute,
}

const AppPlusRouteWithChildren =
  AppPlusRoute._addFileChildren(AppPlusRouteChildren)

interface AppStickersRouteChildren {
  AppStickersCreateRoute: typeof AppStickersCreateRoute
  AppStickersIndexRoute: typeof AppStickersIndexRoute
}

const AppStickersRouteChildren: AppStickersRouteChildren = {
  AppStickersCreateRoute: AppStickersCreateRoute,
  AppStickersIndexRoute: AppStickersIndexRoute,
}

const AppStickersRouteWithChildren = AppStickersRoute._addFileChildren(
  AppStickersRouteChildren,
)

interface AppSupportRouteChildren {
  AppSupportIdRoute: typeof AppSupportIdRoute
}

const AppSupportRouteChildren: AppSupportRouteChildren = {
  AppSupportIdRoute: AppSupportIdRoute,
}

const AppSupportRouteWithChildren = AppSupportRoute._addFileChildren(
  AppSupportRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppCaptureRoute: typeof AppCaptureRoute
  AppCardRoute: typeof AppCardRoute
  AppChallengesRoute: typeof AppChallengesRoute
  AppCoinsRoute: typeof AppCoinsRoute
  AppCommunitiesRoute: typeof AppCommunitiesRouteWithChildren
  AppCreateRoute: typeof AppCreateRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppEventsRoute: typeof AppEventsRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppKaiRoute: typeof AppKaiRoute
  AppListsRoute: typeof AppListsRouteWithChildren
  AppLiveRoute: typeof AppLiveRouteWithChildren
  AppMapRoute: typeof AppMapRoute
  AppMeRoute: typeof AppMeRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlusRoute: typeof AppPlusRouteWithChildren
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStickersRoute: typeof AppStickersRouteWithChildren
  AppStudioRoute: typeof AppStudioRoute
  AppSuperomniRoute: typeof AppSuperomniRoute
  AppSupportRoute: typeof AppSupportRouteWithChildren
  AppVerify2faRoute: typeof AppVerify2faRoute
  AppWatchRoute: typeof AppWatchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCUsernameRoute: typeof AppCUsernameRoute
  AppCallIdRoute: typeof AppCallIdRoute
  AppFlashIdRoute: typeof AppFlashIdRoute
  AppHlIdRoute: typeof AppHlIdRoute
  AppJoinTokenRoute: typeof AppJoinTokenRoute
  AppPIdRoute: typeof AppPIdRoute
  AppStatusIdRoute: typeof AppStatusIdRoute
  AppStoryIdRoute: typeof AppStoryIdRoute
  AppTagTagRoute: typeof AppTagTagRoute
  AppUUsernameRoute: typeof AppUUsernameRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppCaptureRoute: AppCaptureRoute,
  AppCardRoute: AppCardRoute,
  AppChallengesRoute: AppChallengesRoute,
  AppCoinsRoute: AppCoinsRoute,
  AppCommunitiesRoute: AppCommunitiesRouteWithChildren,
  AppCreateRoute: AppCreateRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppEventsRoute: AppEventsRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppKaiRoute: AppKaiRoute,
  AppListsRoute: AppListsRouteWithChildren,
  AppLiveRoute: AppLiveRouteWithChildren,
  AppMapRoute: AppMapRoute,
  AppMeRoute: AppMeRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlusRoute: AppPlusRouteWithChildren,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStickersRoute: AppStickersRouteWithChildren,
  AppStudioRoute: AppStudioRoute,
  AppSuperomniRoute: AppSuperomniRoute,
  AppSupportRoute: AppSupportRouteWithChildren,
  AppVerify2faRoute: AppVerify2faRoute,
  AppWatchRoute: AppWatchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCUsernameRoute: AppCUsernameRoute,
  AppCallIdRoute: AppCallIdRoute,
  AppFlashIdRoute: AppFlashIdRoute,
  AppHlIdRoute: AppHlIdRoute,
  AppJoinTokenRoute: AppJoinTokenRoute,
  AppPIdRoute: AppPIdRoute,
  AppStatusIdRoute: AppStatusIdRoute,
  AppStoryIdRoute: AppStoryIdRoute,
  AppTagTagRoute: AppTagTagRoute,
  AppUUsernameRoute: AppUUsernameRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiMusicDownloadRoute: ApiMusicDownloadRoute,
  ApiMusicStreamRoute: ApiMusicStreamRoute,
  ApiNyxReplyRoute: ApiNyxReplyRoute,
  ApiNyxStreamRoute: ApiNyxStreamRoute,
  ApiOmniStreamRoute: ApiOmniStreamRoute,
  ApiOmniTtsRoute: ApiOmniTtsRoute,
  ApiRtcRoute: ApiRtcRoute,
  SIdRoute: SIdRoute,
  ApiAiStatusRoute: ApiAiStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingAppleRoute: ApiBillingAppleRoute,
  ApiBillingGoogleRoute: ApiBillingGoogleRoute,
  ApiBillingWebRoute: ApiBillingWebRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiMediaCompleteRoute: ApiMediaCompleteRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiVideoTaskIdRoute: ApiVideoTaskIdRoute,
  ApiVideoGenerateRoute: ApiVideoGenerateRoute,
  ApiMusicTrackIdDownloadRoute: ApiMusicTrackIdDownloadRoute,
  ApiVideoStatusTaskIdRoute: ApiVideoStatusTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
